language: android
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
android:
  components:
  - build-tools-26.0.2
  - android-26
before_deploy:
  - export TARGET_FOLDER=/Builds_$DROPBOX_OAUTH_BEARER
  - echo "deploying $TARGET_FOLDER to Dropbox"
before_install:
- rvm install 2.2.6
- gem install dropbox-deployment
- openssl aes-256-cbc -K $encrypted_775ae62386c6_key -iv $encrypted_775ae62386c6_iv
  -in key.jks.enc -out key.jks -d
script:
- "./gradlew assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: QIINSt1nCJvRYz6bCWCgBhdHEnvb2qD3IvGtneonEjub8cREIS/dFbZ9iu/n0HrjRWy39j088HkT2DeMIr2GI3Q7TD3uKSf8jzlcijVNhFi7p4gGaC4x1mXeI1mLqcR/0RaaEBLs6hf1UkPBclrwejUiaO9cQ7adlcvw+rhyMS7+gzkQx7yekOwT4rD6Tl0dRTABVLFCceUELdvDdMV++NK9fE7/kA9hAIRdo0oEhU2G/Jd2g9w2Cjb868l8W5K1AR4NiaUqmUdnYrUrO1yEs6RMKzvvngJCAh8BGvxMDNCsaOhZrKnAK8z4TKJtv9daTyXUXJnNXRY+N4EC/HGobnBa2mpWT3TGMv/xnCBCDjmyxeq72uE0WrDJcGUy666ukWqULXDYFLOTRlS0khuxVgj2t4x6s170dI+JJPOCqySJ6VuDv3ZsPGZ66QZP3Y5ZZ36+SV3lriTWv6AwhrPO+GmOCtfMsaSDFelXbe1s/vB1URTeNfJWxoyY5g4/0WdDiNHMjmmI4sAP8lHWPacYEGPKe/0qBReQHXrvZlojY81IHcSae3QTazWK6A5xW61SXSNRKcxEvmLINHtIy8xDZZ13IPK4topr4hrmsxVHKR5dF06h+td0eu8oSzjyAejsWbMf0qnkbVR1edtbJCCtdLEYSAtQOgBkJiWpxmcbPOo=
  file: pushpull/build/outputs/apk/release/pushpull-release.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy:
  - dropbox-deployment